version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./app:/app
      - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - php

  php:
    image: php:7-fpm
    volumes:
      - ./app:/app